### ISSUE TITLE
Names aren't sanitized in ;clubs

### ISSUE THREAD

**Issue by saramaebee** [ryry013/Rai#23]
<img width="477" alt="image" src="https://github.com/r-hensley/Rai/assets/34497797/510eaee8-4192-4799-bd9c-e82d38bc36aa">
Because my username has two underscores, my name get's italicized and the underscores are hidden.

No need to take action, it's super low prio obviously and I'll probably try to correct it soon

**Comment by r-hensley** [comment]
Easiest solution would probably be to just replace all `_` and `*` in the names with `\_` and `\*`

**Comment by r-hensley** [comment]
Fixed in commit https://github.com/r-hensley/Rai/commit/f77c183a3beda0720c526de26558270f1247d4ad

**Comment by r-hensley** [comment]
![image](https://github.com/r-hensley/Rai/assets/30587035/6a542254-bc5a-46c8-83fa-d19fc71ce2d5)
